config/routes.rb
Huick::Application.routes.draw do

	
	root :to => "posts#recent"
	get "recent(.:format)" => "posts#recent"
	get "p/:postid(.:format)" => "posts#post"
	get "pointy/:postid" => "posts#pointy"
	get "u/:username(.:format)" => "users#user"
	get "u/:username/p(.:format)" => "users#posts"
	get "u/:username/r(.:format)" => "users#recommendations"
	get "u/:username/s" => "users#subscriptions"
	get "u/:username/tags" => "tags#index"
	get "u/:username/tags/:tag_text(/index.:format)" => "tags#posts"
	get "tags/:tag_text(/index.:format)" => "tags#posts"
	get "tags" => "tags#index"
	get "login/:access_token" => "sessions#login"
	get "validate" => "application#selfvalidate"
	post "validate" => "application#selfvalidate"
	get "unhide" => "application#unhide"
	get "search" => "application#search"
end

app/models/post.rb
class Post < ActiveRecord::Base
	scope :noprivates, -> { where(:private => false) }
	
	belongs_to :user
	has_and_belongs_to_many :tags,  -> { distinct }, :join_table => :posts_tags
	has_many :comments, -> { distinct.order("number ASC") }, :dependent => :destroy
# 	attr_accessor :resource, :post_content, :postid, :comment_counter, :target_user, :is_backup
	has_and_belongs_to_many :subscribers, -> { distinct }, :class_name => "User", :join_table => :post_subscriptions
	has_many :post_recommendations, :dependent => :destroy
	has_and_belongs_to_many :recommending_users, -> { distinct }, :class_name => "User", :join_table => :post_recommendations
	has_and_belongs_to_many :ackd_users,  -> { distinct }, :class_name => "User", :join_table => :post_acknowledgements
	belongs_to :target_user, :class_name => "User"

  before_create :assign_postid

  def self.next_postid
	postid = nil
	tentative_number = ActiveRecord::Base.connection.execute("SELECT reltuples AS approximate_row_count FROM pg_class WHERE relname = 'posts'").first.first.last.to_i
	begin
		postid = rand(tentative_number * 10 + 100)
	end while Post.where(postid: postid).first
	# Ok, this should be in transaction, but c'mon, what's the chance. But put this in transaction.
	postid
  end
  
	def assign_postid
		return if self.postid
		self.postid = Post.next_postid
	end
  
	def postid_text
		Huick.int_to_postid(postid)
	end
	
	def self.by_postid(which_postid)
		self.where(:postid => Huick.postid_to_int(which_postid)).first
	end
	
	def add_tag(tag_text)
		tag = Tag.find_or_create_by(:tag_text => tag_text)
		unless self.tags.exists? tag.id
			self.tags << tag
		end
	end
	
	def del_tag(tag_text)
		tag = Tag.find_or_create_by(:tag_text => tag_text)
		self.tags.delete tag
	end
	
	def sorted_recommendations
		recs = []
		silents = []
		self.post_recommendations.each do |c_rec|
			if c_rec.recommending_comment
				recs << [c_rec.user, c_rec.recommending_comment]
			else
				silents << c_rec.user
			end
		end
		[recs, silents]
	end
	
	def hidden_by?(some_user)
		return false unless some_user
		self.user.hidden_by? some_user or self.tags.map{|tag| tag.hidden_by?(some_user) }.any?
	end
	
	def accessible_by?(some_user)
		!self.private? or self.user == some_user or self.target_user == some_user
	end
	
	def self.search(terms)
		dictionary = 'english'
		if terms =~ /[а-яА-Я]/i
			dictionary = 'russian'
		end
		r = self.select("setweight(to_tsvector('#{sanitize_sql dictionary}', coalesce(post_content, '')), 'A') <=> plainto_tsquery('#{sanitize_sql dictionary}', '#{sanitize_sql terms}') AS rank, posts.*")
		return r.where("setweight(to_tsvector(:dictionary, coalesce(post_content, '')), 'A') @@ plainto_tsquery(:dictionary, :terms)", dictionary: dictionary, terms: terms)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include PostsHelper
	include ApplicationHelper
	include ActionView::Helpers::TextHelper
	def post
		@post = Post.where(:postid => Huick.postid_to_int(params[:postid])).preload(:post_recommendations, :user).first
		raise ActionController::RoutingError.new('Not Found') unless @post
		
		raise ActionController::RoutingError.new('Forbidden') unless @post.accessible_by? @current_user
		
		@comments = if @unhide or not @current_user then
			@post.comments
		else
			Huick.hide(@post.comments, @current_user)
		end.preload(:comment_recommendations, :user, :parent_comment_recommendation, :parent_post_recommendation, :parent_comment_user, :post)
		
		respond_to do |format|
			format.html
			format.atom
		end
	end
	
	def recent
		sorted_posts = Post.order("created_at DESC").noprivates.preload(:tags, :user)
		
		hidden_posts = if @unhide or not @current_user then
			sorted_posts 
		else
			Huick.hide(sorted_posts, @current_user)
		end
		
		if request.format.atom?
			@posts = hidden_posts.limit(25)
		else
			@posts = hidden_posts.page(params[:page])
		end
		

		respond_to do |format|
			format.html
			format.atom
		end
	end
	
	def pointy
		redirect_to(action: :post, postid: Huick.int_to_postid(Huick.pstoid_to_int(params[:postid])))
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/views/posts/post.html.erb
<% if not @unhide and @post.hidden_by? @current_user %>
	<% content_for :title, "Huick: Hidden post" %>
	<div class="content-hidden">
	This page have been hidden according to your criteria. See <a href="<%= unhide_path(url_for) %>">unhidden version of it if you're still interested.
	</div>
<% else %>
	<% content_for :title, "@#{@post.user.username} ##{@post.postid_text} -- #{truncate(@post.post_content, length: 25)}" %>
	<% content_for :feed_title, "@#{@post.user.username} ##{@post.postid_text} -- #{truncate(@post.post_content, length: 25)}" %>
	<% content_for :feed_url, url_for(:format => :atom) %>
	
	<div class="post">
		<%= render partial: "post", locals: {post: @post, full_text: true} %>
		<div class="post-recommendations">
			<% unless @post.sorted_recommendations[0].reject{|a| not @unhide and a[0].hidden_by? @current_user}.empty? and @post.sorted_recommendations[1].reject{|a| not @unhide and a.hidden_by? @current_user}.empty? %>
			Recommended by:
			<%= @post.sorted_recommendations[0].reject{|a,b| not @unhide and a.hidden_by? @current_user}.map do |u, cmt| "<div class='post-recommendation'>#{link_to ("@"+u.username), user_path(u)} #{link_to ("#"+cmt.cmtid_text), comment_path(cmt)}: #{mark_it_up cmt.comment_text}</div>" end.join("\n").html_safe %>
			<div class='post-silent-recommendations'>
			<%= @post.sorted_recommendations[1].reject{|a| not @unhide and a.hidden_by? @current_user}.map do |u| "#{link_to ("@"+u.username), user_path(u)}" end.join(",").html_safe %>
			</div>
			<% end %>
		</div>
	</div>
	
	<div class="comments">
	
	<% @comments.each do |comment| %>
	<div class="comment">
		<%= render partial: "comment", locals: {comment: comment, full_text: true} %>
	</div>
	<% end %>
	
	</div>
<% end %>

app/views/posts/recent.html.erb
<% content_for :title, "Huick: recent" %>
<% content_for :feed_title, "Huick: recent" %>
<% content_for :feed_url, url_for(:format => :atom) %>



<% if not params[:search] and not params[:page] %>

<div class="search">
<form action="<%= url_for controller: :application, action: :search %>" method="get">
	<%= text_field_tag :search %>
	<%= submit_tag "Search", :name => "" %>
	<%= label_tag :kind_posts, "posts" %>
	<%= radio_button_tag :kind, "posts", true %>
	<%= label_tag :kind_comments, "comments" %>
	<%= radio_button_tag :kind, "comments", false %>
</form>
</div>

<div class="welcome">
<%= render partial: "welcome" %>
<% end %>

<% @posts.each do |post| %>
<div class="post">

<%= render partial: "post", locals: {post: post} %>

</div>
<% end %>

<%= paginate @posts %>